### ISSUE TITLE
Aborting (throwing errors) within a transform

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/markdown-transform#229] opened 2020-06-10 20:15 UTC
The `markdown-cicero` transform currently requires that a `clause` tag has both `src` and `clauseid` attributes. 
```
<clause src="foo" clauseid="bar"/>
```
However, this can lead to id conflicts when adding multiple instances of the same tag to a document, it also means that if a user doesn't provide the `clauseid`, then the tag is not recognised as a `clause` tag and falls back to a code block (this behaviour is due to the markdown principle that every document should be valid). 

To solve this, I posted a naive solution that allows the `clauseid` to be optional, and to default to a uuid (https://github.com/accordproject/markdown-transform/pull/228). However, this breaks our principle of round-tripping stability.

An alternative solution would be to recognise the `clause` tag as an extension to commonmark spec and allow the transform to halt or throw an error when there are missing or invalid attributes. But this breaks the graceful fallback principle 😕 .

Any thoughts?

**Comment by irmerk** [comment] 2020-06-11 12:59
Just a note that the `clauseid` attribute is changing to `name, referenced [here](https://github.com/accordproject/cicero/issues/547#issuecomment-632256643)

What does this mean?
> ... this can lead to id conflicts when adding multiple instances of the same tag to a document ...

I think we don't want to allow multiple instances of the exact same clause in a document.

Also, I'm not sure why we want the user to control the `clauseid`/`name` because it _should_ be unique.

**Comment by jeromesimeon** [comment] 2020-08-11 18:32
The current version `0.12.*` follows the "gracefully fallback" principle. Although we could change this behaviour, this is inline with all other markdown extensions I found for `markdown-it` (and generally in line with best practices for markdown extensions).

To some extent the https://templatemark-dingus.netlify.app can allow users to check whether their contract or grammar is parsed as expected.

Could this be considered a valid resolution for this issue, or should we have a follow up discussion about this?

**Comment by jeromesimeon** [comment] 2021-08-18 02:34
@mttrbrts I'm wondering if the current behavior would be acceptable, based on the above note about commonmark and whether we could close this issue.

I think the problem is somewhat alleviated by the new parser and template mark dingus which can help identify when a `{{clause}}` tag is parsed as text?

**Closed** 2021-08-18 14:03 UTC
Labels: Type: Question ❓, Type: Discussion 🗣
